ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'FIRE_SMOKE';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'SMOKE';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'CROWD';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'FIGHT';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'FALL';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'INTRUSION';
ALTER TYPE "IncidentType" ADD VALUE IF NOT EXISTS 'LOITERING';

ALTER TABLE "SecurityIncident"
ADD COLUMN "confidenceScore" DOUBLE PRECISION;